name: Avalon
main: me.aventium.avalon.Avalon
version: 0.4
author: Aventium
commands:
  team:
    description: Team commands
    aliases: [t]
  koth:
    description: Manage KOTH in-game
  region:
    description: Manage regions
  removedeathban:
    description: Remove a players current deathban
    aliases: [rmdeathban, rmdb]